### ISSUE TITLE
argument order in location and move different

### ISSUE THREAD

**Issue by MaxNoe** [erikrose/blessings#113]
Why is the order of the arguments different in `move` and  `location`?

This is really unintuitive and makes the code really difficult to read. Especially 
since move does not even have keyword arguments.

**Comment by erikrose** [comment]
Legacy. I designed location() and later discovered move, which is a built-in capability and so can't have its order changed. We'll correct it in 2.0.

**Comment by jquast** [comment]
Closing as duplicate of #58
