### ISSUE TITLE
Terminal not updated

### ISSUE THREAD

**Issue by sphh** [erikrose/blessings#119]
I wanted to write a little swirly progress indicator which successively displays |, /, -, and \. The following code is an example of what I had in mind:

    from blessings import Terminal

    term = Terminal()
    indicators = '|/-\\'
    with term.hidden_cursor():
        print('Working'+term.move_x(term.width-1), end='')
        i = 0
        while True:
            print(term.move_left + indicators[i], end='')
            i += 1
            i %= len(indicators)

This works well, but if I include a `time.sleep(1)` into the `while`-loop, the line in the terminal remains empty – no swirling indicators and not even the preamble `'Working'`:

    import time
    from blessings import Terminal

    term = Terminal()
    indicators = '|/-\\'
    with term.hidden_cursor():
        print('Working'+term.move_x(term.width-1), end='')
        i = 0
        while True:
            print(term.move_left + indicators[i], end='')
            time.sleep(1)
            i += 1
            i %= len(indicators)

I got it working by including the line `sys.stdout.flush()` after the print statement. Is that the correct way to handle this scenario?

Thanks,
Stephan

**Comment by jquast** [comment]
Yes, it is.

You may alternatively specify flush=true keyword argument to the print() function.

Rules of try driver: standard out is line buffered (flushed only after beeline is reached), standard error is unbuffered (no flush necessary).

**Comment by sphh** [comment]
Thanks!

What confused me was, that it worked without `time.sleep(1)` but not with.

BTW, the `flush` keyword argument was introduced in Python 3.3, but not backported. I found the solution for a print function with the `flush` keyword here: http://stackoverflow.com/a/35467658/541136
