### ISSUE TITLE
term.number_of_colors raises if term._does_styling is False

### ISSUE THREAD

**Issue by ahal** [erikrose/blessings#124]
I've identified this as the root cause of:
https://bugzilla.mozilla.org/show_bug.cgi?id=1425836

I have a formatter that calls term.number_of_colors. This normally works, but if `term._does_styling` is False, then we never call `setupterm`. This means the call to `tigetnum` in the `number_of_colors` property will fail. We should probably just return 0 in this case.

**Comment by ahal** [comment]
Not sure the proper way to link a PR to an issue, but I pushed:
https://github.com/erikrose/blessings/pull/125

**Comment by erikrose** [comment]
Fixed in #125.
