### ISSUE TITLE
What does 'wingo' do? (appears in README.rst)

### ISSUE THREAD

**Issue by gregsadetsky** [erikrose/blessings#130]
Thanks for the great library!

In [README.rst](https://github.com/erikrose/blessings/blob/master/README.rst), in the second top-most example, the following line appears:

    print t.wingo(2)

Is it possible that this line does not do anything in the latest version? Under OSX, both 't.wingo' and 't.wingo()' simply return an empty unicode string.

Thank you!

**Comment by erikrose** [comment]
It depends entirely on your terminal. I don't think wingo does anything on most modern terminals, so it probably wasn't a great choice for an example. It looks like I was just trying to illustrate the low-level control that's available if you want it. A little background on wingo: https://unix.stackexchange.com/questions/391850/which-terminals-or-terminal-emulators-support-hardware-windows. Thanks for using blessings! :-D
