### ISSUE TITLE
[feature request] convenience wrapper?

### ISSUE THREAD

**Issue by AlJohri** [erikrose/blessings#141]
@erikrose I often import this at the top of each of my scripts and cli utilities and I'd prefer to not have to call `t = Terminal()` atop each script. would you be open to a convenience wrapper module that calls the class? something like:

```python
from blessings import Terminal
sys.modules[__name__] = Terminal()
```

Then I can use this downstream as:

```python
import blessings.terminal as t
print(t.cyan('hey there'))
print(f"this is now {t.red('colored') text"!)
```

**Comment by erikrose** [comment]
That is convenient, but there’s a reason we can’t pull it off. Calling the Terminal constructor calls setupterm(), which has global and irreversible side effects scoped to the entire proces. Specifically, once setupterm has been called, no further calls to it will ever do anything. (This is a CPython bug and has been open forever.) For example, if you wanted to set up with a different terminal type, you’d be out of luck. Sorry to be the bearer of bad news!

**Comment by AlJohri** [comment]
@erikrose can you explain a little further? as far as I understand it, if `terminal.py` is a separate module, as long as it is not imported, the "global and irreversible side effects scoped to the entire process" will not take place. you would only use the shortcut of importing terminal.py in a short script where the terminal type will never be modified

- usual use: `import blessings import Terminal; t = Terminal()`
- convenience use (via separate module `terminal.py`): `import blessings.terminal as t`
