### ISSUE TITLE
Printing progress bars to stderr

### ISSUE THREAD

**Issue by nurmians** [erikrose/blessings#142]
I stumbled here while looking for a solution to showing separate progress bars on multiple lines while my python script churns at its multiple parallel tasks. I was wondering if it is possible to do this in blessings by using only stderr while stdout is piped along to the next program?

**Comment by erikrose** [comment]
I can't see any reason that shouldn't work. Best of luck!

**Comment by nurmians** [comment]
What I was trying to say was I couldn't find a way to do it. I would appreciate a hint on how to get started =)

**Comment by ont** [comment]
@nurmians sorry for offtopic, if you need just one progress bar in your project then it may be better to use https://tqdm.github.io/

**Comment by nurmians** [comment]
I'm trying to achieve something like this (multiple parallel progress indicators), while still being able to write output to stdout:
```
[boot-1.pkg] 3.66 MB / 128.94 MB [==>------------------------------------------------] 2.84 % 759.61 KB/s 2m48s
[boot-2.pkg] 23.66 MB / 48.94 MB [===================>-------------------] 45.84 % 629.61 KB/s 2m48s
[boot-3.pkg] 30.00 MB / 300.94 MB [=====>------------------------------------------] 10.84 % 459.61 KB/s 2m48s
```

**Comment by ont** [comment]
@nurmians read docs of tqdm on github, it supports multiple progressbars and outputs to stderr by default.

**Comment by nurmians** [comment]
@ont ok, thanks I'll check it out =)
