### ISSUE TITLE
Question: can I print raw escape codes (ANSI?) direct to the terminal with blessings?

### ISSUE THREAD

**Issue by bradwood** [erikrose/blessings#143]
Details:

I've been using curses and getting along okay with it, but now I've started using a markdown renderer that is optimised for terminal output. It works well when it writes straight to STDOUT. However, I want to control _where_ on a terminal screen this is outputted. ncurses doesn't support passing in of escape codes generated elsewhere so I am looking for a replacement that needs to be able to do this.

Can blessings meet this need?  My initial attempts seem to suggest not but I hope I'm wrong!

Many thanks

**Comment by erikrose** [comment]
Blessings is a pretty lightweight wrapper and doesn't handle things like text wrap or scrolling on its own. However, you can certainly use it to position the cursor before dumping your rendered Markdown codes to the screen. Blessings certainly won't interfere with the escape codes generated elsewhere; it won't even get the chance, as you'll likely just be passing them to `print`. If you want something a lot heavier with widgets and subwindows and such, take a look at urwid. Good luck!

**Comment by bradwood** [comment]
Ok cool, and there is no dependency on the builtin curses, or any libs that depend on c-based curses(-like) library?
