### ISSUE TITLE
Error _curses

### ISSUE THREAD

**Issue by dafmdev** [erikrose/blessings#163]
![image](https://user-images.githubusercontent.com/28261742/130387562-99373004-ac44-4c38-92bb-e86bf89e19d4.png)
Cuando intento usar la librería blessings me sale este error.
Me ayudas por favor

**Comment by erikrose** [comment]
Unfortunately, blessings does not support Windows, because it is a thin convenience layer over curses, which, as you have found, Windows does not provide. I recommend you try colorama, which works at a higher level of abstraction and supports Windows. Sorry you had trouble!
