### ISSUE TITLE
escape code grokking textwrap

### ISSUE THREAD

**Issue by willkg** [erikrose/blessings#19]
Terminal knows a lot about your terminal. It'd be super duper if it had a textwrap function that knew about your terminal and also grokked escape codes.

e.g.

```
t = Terminal()
print t.textwrap(t.bold('foo') + ' some really long text...')
```

would textwrap at the appropriate width for the terminal ignoring the escape codes from bold.

**Comment by jquast** [comment]
This is resolved in 'blessed-integration' branch.

**Comment by jquast** [comment]
The `blessed` fork of `blessings` contains terminal functions `wrap`, `ljust`, `rjust`, `center`, which are all terminal-aware. Additional functions `length` and `strip_seqs` and `split_seqs` are available. https://blessed.readthedocs.io/en/latest/measuring.html#measuring

**Comment by willkg** [comment]
Awesome! I'll close this out.
