### ISSUE TITLE
Example not working in tmux

### ISSUE THREAD

**Issue by erikrose** [erikrose/blessings#24]
From http://www.reddit.com/r/programming/comments/yeudv/blessings_15_a_python_replacement_for_curses/c5vd2lv:

> Hey, as long as we're making suggestions / reporting bugs... the first code example in the readme is actually broken for me when I run the code in a tmux session, and no text is displayed. Seems to have to do with the x coordinate being set to 0 -- when I set it to 1 instead, the code works. 0 works fine in a normal terminal session. Thought you might like to know! Thanks for the sweet code!

**Comment by jquast** [comment]
This also works fine for me tmux 1.9a on OSX using TERM=screen. I am closing this issue, will re-open if anybody can define exactly how to reproduce.
