### ISSUE TITLE
Blessings fails to setup term if TERM is not set?

### ISSUE THREAD

**Issue by erikrose** [erikrose/blessings#39]
See if https://bugzilla.mozilla.org/show_bug.cgi?id=878089 is still true and if there's anything we can do internally to fix it, if it is.

**Comment by jquast** [comment]
This (and related issues) resolved in 'blessed-integration' branch, https://github.com/erikrose/blessings/blob/blessed-integration/blessings/formatters.py#L144-148

**Comment by xsuchy** [comment]
I tried to replace ` environ.get('TERM', 'unknown')` with ` environ.get('TERM', 'linux')` and it works for me.
