### ISSUE TITLE
Provide Convenience For Fixed Positioning

### ISSUE THREAD

**Issue by JakeWharton** [erikrose/blessings#66]
It would be extremely convenient to provide a mechanism for which one could render to a fixed position on the screen, regardless of scrolling text beneath it.

This is a bit more complex than just moving the cursor and rendering since newlines currently bump everything up at once.

A contrived example would be a program that prints 1000 lines but maintains a fixed percentage at the bottom of the screen.

**Comment by jquast** [comment]
@JakeWharton please let us know if this issue may be closed.
