### ISSUE TITLE
cursor changed in the bottom

### ISSUE THREAD

**Issue by pingf** [erikrose/blessings#69]
Hi, I've been implementing something like interactive menu. for nodejs there's a package called inquirer, and for python there's one called python-inquirer which is based on this. However, it only show the menu in the bottom. I wrote some codes in the below gist. this works fine when I input command in the above,
however if I the input in the bottom of the shell, the cursor will move and the menu will we render again. any guys knows why?_?
https://gist.github.com/pingf/aeb6d3a1068f6f8c1c0c

**Comment by jquast** [comment]
```
-#os.system('clear')
+print(terminal.clear)
```

or

```
-    with terminal.location():
+    with terminal.location(0, 0):
```

**Comment by jquast** [comment]
@pingf please us know if this issue may be closed.

**Comment by pingf** [comment]
thx, but I know that, I don't want to let it show in the 0,0 position(I want the just in place menu, but when it reaches bottoms, bad things happened), and I don't want clear the previous screen, that's why I comment it. however, node's lib inquerier can do it~

**Comment by jquast** [comment]
term.csr (set scrolling region) is probably what you're looking for.
