### ISSUE TITLE
Pare down readme, and expand Sphinx docs

### ISSUE THREAD

**Issue by erikrose** [erikrose/blessings#78]
Make the readme a short, motivating pitch, showing off blessings' capabilities and elegance. Move the rest to the Sphinx docs.

Blocks #72.

**Comment by jquast** [comment]
Pull request https://github.com/erikrose/blessings/issues/93 is awaiting your merge to close this issue.

**Comment by jquast** [comment]
Closed by #100, review at http://1984.ws/blessings/index.html
