### ISSUE TITLE
 Factor up py2/py3 switches

### ISSUE THREAD

**Issue by erikrose** [erikrose/blessings#80]
We do things like this in a few places:

```python
if sys.version_info[0] == 3:
    text_type = str
    basestring = str
else:
    text_type = unicode  # noqa
```

Let's depend on and use `six`. There's no reason to be afraid of dependencies.

Blocks #72.

**Comment by jquast** [comment]
Pull request https://github.com/erikrose/blessings/issues/89 is still awaiting your merge to close this issue.
