### ISSUE TITLE
Polish docstrings for grammar and flow.

### ISSUE THREAD

**Issue by erikrose** [erikrose/blessings#84]
They should read beautifully in the Sphinx docs.

Blocks #72.

**Comment by jquast** [comment]
Mostly complete, only ``sequences.py`` remains and ``terminal.py`` is partially completed in branch ``blessed-integration-pep257-docstrings``.

pep257 compliance is easily tested using ``tox -e sa``. I've been using sphinx references such as ``:returns``, ``:param`` and cross-referencing ``:func`` and ``:class`` where possible, though I have not yet rendered and reviewed. Documents are rendered using ``tox -edocs``, where "warnings are errors" and fails travis testing for any issues discovered by sphinx.  For this reason this branch includes the unmerged pull request https://github.com/erikrose/blessings/pull/93.  Furthermore, as a lot of re-ordering and docstrings are done for styling guides, the unmerged pull request https://github.com/erikrose/blessings/pull/89 is also included in this branch.

**Comment by jquast** [comment]
Closed by PR #100, review at http://1984.ws/blessings/index.html
